// Personalize this file with her details ✨
export const birthdayConfig = {
  herName: "Srividya",
  yourName: "Ajaykumar",
  meetingDate: "2025-05-11T00:00:00",
  birthdayMessage:
    "Happy Birthday, my whole world. Today the universe celebrates the day it became infinitely better.",
  loveLetter: [
    "The story of how we met, from my side.",
    "I’ve never really been someone who easily talks to girls, and most connections never lasted. So I never truly understood that kind of bond. But I guess the universe had its timing.",
    "On 11 May 2025, when you came up to me and asked about my PPT, I still remember how speechless I was. You kept asking, kept the conversation going, and somehow made it easy for me.",
    "Over time, you understood my thoughts and who I am. And when you gave me your number — it was the first time something like that ever happened to me.",
    "That day, I found myself waiting to see you again, just to talk more.",
    "That’s how you came into my life — simple, unexpected, but truly meaningful.",
    "This is one of my first memories of you, and it means a lot to me — as a friendship I genuinely value.",
  ],
  memories: [
    {
      date: "The Day We Met",
      caption: "I didn't know it yet, but my life had just changed.",
      image: "/photos/memory_20.jpg",
    },
    {
      date: "Our First Date",
      caption: "I couldn't stop smiling for days afterward.",
      image: "/photos/memory_12.jpg",
    },
    {
      date: "That Late-Night Drive",
      caption: "Windows down, your laugh louder than the music.",
      image: "/photos/memory_33.jpg",
    },
    {
      date: "The Little Things",
      caption: "From late-night talks to standard texts that always made me smile.",
      image: "/videos/video_143.mp4",
    },
    {
      date: "The Quiet Sunday",
      caption: "Coffee, your head on my shoulder. Heaven.",
      image: "/photos/memory_27.jpg",
    },
    {
      date: "Our First Trip",
      caption: "Every photo had you smiling. Every memory does too.",
      image: "/photos/memory_31.jpg",
    },
    {
      date: "Today",
      caption: "And every day after this one. I promise.",
      image: "/photos/memory_18.jpg",
    },
  ],
  coupons: [
    { title: "One Movie Night", note: "Your pick. Snacks on me." },
    { title: "One Surprise Date", note: "Planned entirely by me. Just say yes." },
    { title: "One Royal Day", note: "You choose everything. I obey. 👑" },
    { title: "Breakfast in Bed", note: "Redeem any lazy Sunday." },
    { title: "Endless Hugs", note: "No expiration. Ever." },
    { title: "One Hand-Written Letter", note: "Old-school. From the heart." },
  ],
  secretLetters: [
    {
      title: "What I Admire",
      intro: "A small note on your character...",
      content:
        "Your absolute resilience. No matter how tough life gets or how many red errors pop up in your console, you find a way to smile, crack a joke, and push through. You inspire me to be better every day.",
    },
    {
      title: "Lessons Learned",
      intro: "Things you taught me...",
      content:
        "You taught me that true friendship isn't about being identical or always agreeing. It's about accepting each other's chaos, standing strong during storms, and knowing when to order a pizza to fix a bad mood.",
    },
    {
      title: "Unspoken Gratitude",
      intro: "Things I never told you...",
      content:
        "There were days when I was completely overwhelmed and ready to give up. Just a random dumb meme or a dry sarcastic text from you completely changed my night. Your silent support means more than you know.",
    },
    {
      title: "Why You Matter",
      intro: "The bottom line...",
      content:
        "Because in a world of temporary connections and ghosting, you are a constant. You are family. Happy Birthday, my friend. Here's to standing by each other for all the years to come.",
    },
  ],
  music: {
    pageSongs: [
      {
        title: "He Will Never Leave Me Alone",
        url: "/music/background/he_will_never_leave_me_alone.mp3",
      },
      { title: "Last 7 Minutes", url: "/music/background/last_7_minutes.mp3" },
      { title: "Nallaru Po X Oorum Blood", url: "/music/background/nallaru_po_x_oorum_blood.mp3" },
      { title: "Please Don't Forget Me", url: "/music/background/please_dont_forget_me.mp3" },
      { title: "The Metro Proposal", url: "/music/background/the_metro_proposal.mp3" },
    ],
    cassetteSongs: [
      {
        title: "Kannukulla (Reprise)",
        situation: "A beautiful reprise dedicated just for you",
        url: "/music/three_songs/kannukulla_reprise.mp3",
      },
      {
        title: "Nallaru Po",
        situation: "For our classic unplugged vibe",
        url: "/music/three_songs/nallaru_po.mp3",
      },
      {
        title: "Yedi",
        situation: "Our special heartbeat track",
        url: "/music/three_songs/yedi.mp3",
      },
    ],
  },
  galleryItems: [
    { type: "photo", url: "/photos/memory_2.jpg", aspectRatio: 0.71 },
    { type: "video", url: "/videos/video_1.mp4", aspectRatio: 1.778 },
    { type: "photo", url: "/photos/memory_3.jpg", aspectRatio: 0.939 },
    { type: "photo", url: "/photos/memory_4.jpg", aspectRatio: 0.594 },
    { type: "photo", url: "/photos/memory_1.jpg", aspectRatio: 1.778 },
    { type: "photo", url: "/photos/memory_21.jpg", aspectRatio: 1.066 },
    { type: "photo", url: "/photos/memory_5.jpg", aspectRatio: 1.778 },
    { type: "video", url: "/videos/video_2.mp4", aspectRatio: 1.778 },
    { type: "photo", url: "/photos/memory_26.jpg", aspectRatio: 1.239 },
    { type: "photo", url: "/photos/memory_6.jpg", aspectRatio: 0.563 },
    { type: "video", url: "/videos/video_3.mp4", aspectRatio: 1.778 },
    { type: "photo", url: "/photos/memory_31.jpg", aspectRatio: 0.939 },
    { type: "photo", url: "/photos/memory_7.jpg", aspectRatio: 0.563 },
    { type: "video", url: "/videos/video_4.mp4", aspectRatio: 1.778 },
    { type: "photo", url: "/photos/Screenshot (74).png", aspectRatio: 1.165 },
    { type: "photo", url: "/photos/memory_8.jpg", aspectRatio: 0.563 },
    { type: "video", url: "/videos/video_5.mp4", aspectRatio: 1.778 },
    { type: "photo", url: "/photos/memory_9.jpg", aspectRatio: 1.778 },
    { type: "video", url: "/videos/video_6.mp4", aspectRatio: 1.778 },
    { type: "photo", url: "/photos/memory_10.jpg", aspectRatio: 1.778 },
    { type: "video", url: "/videos/video_7.mp4", aspectRatio: 1.778 },
    { type: "photo", url: "/photos/memory_11.jpg", aspectRatio: 1.778 },
    { type: "video", url: "/videos/video_8.mp4", aspectRatio: 1.778 },
    { type: "photo", url: "/photos/memory_12.jpg", aspectRatio: 1.778 },
    { type: "video", url: "/videos/video_9.mp4", aspectRatio: 1.778 },
    { type: "photo", url: "/photos/memory_13.jpg", aspectRatio: 0.64 },
    { type: "video", url: "/videos/video_10.mp4", aspectRatio: 1.778 },
    { type: "photo", url: "/photos/memory_14.jpg", aspectRatio: 0.688 },
    { type: "video", url: "/videos/video_11.mp4", aspectRatio: 1.778 },
    { type: "photo", url: "/photos/memory_15.jpg", aspectRatio: 1.778 },
    { type: "video", url: "/videos/video_12.mp4", aspectRatio: 1.778 },
    { type: "photo", url: "/photos/memory_17.jpg", aspectRatio: 0.563 },
    { type: "video", url: "/videos/video_13.mp4", aspectRatio: 1.778 },
    { type: "photo", url: "/photos/memory_28.jpg", aspectRatio: 0.737 },
    { type: "video", url: "/videos/video_14.mp4", aspectRatio: 1.778 },
    { type: "photo", url: "/photos/memory_30.jpg", aspectRatio: 0.563 },
    { type: "video", url: "/videos/video_15.mp4", aspectRatio: 1.778 },
    { type: "photo", url: "/photos/memory_34.jpg", aspectRatio: 0.477 },
    { type: "video", url: "/videos/video_16.mp4", aspectRatio: 1.778 },
    { type: "photo", url: "/photos/memory_16.jpg", aspectRatio: 1.778 },
    { type: "video", url: "/videos/video_17.mp4", aspectRatio: 1.778 },
    { type: "video", url: "/videos/video_18.mp4", aspectRatio: 1.778 },
    { type: "photo", url: "/photos/memory_18.jpg", aspectRatio: 1.5 },
    { type: "photo", url: "/photos/memory_19.jpg", aspectRatio: 1.778 },
    { type: "photo", url: "/photos/memory_20.jpg", aspectRatio: 2.222 },
    { type: "photo", url: "/photos/memory_22.jpg", aspectRatio: 2.222 },
    { type: "photo", url: "/photos/memory_23.jpg", aspectRatio: 2.222 },
    { type: "photo", url: "/photos/memory_24.jpg", aspectRatio: 2.222 },
    { type: "photo", url: "/photos/memory_25.jpg", aspectRatio: 2.222 },
    { type: "photo", url: "/photos/memory_27.jpg", aspectRatio: 1.778 },
    { type: "photo", url: "/photos/memory_29.jpg", aspectRatio: 1.586 },
    { type: "photo", url: "/photos/memory_32.jpg", aspectRatio: 2.222 },
    { type: "photo", url: "/photos/memory_33.jpg", aspectRatio: 1.778 },
    { type: "photo", url: "/photos/Screenshot (89).png", aspectRatio: 1.449 },
    { type: "photo", url: "/photos/Screenshot (95).png", aspectRatio: 1.436 },
    { type: "photo", url: "/photos/Screenshot (112).png", aspectRatio: 2.073 },
    { type: "photo", url: "/photos/Screenshot (114).png", aspectRatio: 2.062 },
    { type: "photo", url: "/photos/Screenshot (117).png", aspectRatio: 2.089 },
    { type: "photo", url: "/photos/Screenshot (123).png", aspectRatio: 1.553 },
    { type: "photo", url: "/photos/Screenshot (126).png", aspectRatio: 1.595 },
  ],
  tenRupeeNote: {
    serialNumber: "02D 648892",
    firstHalfImage: "/first-half-note.png",
    secondHalfImage: "/second-half-note.png",
    fullNoteImage: "/full-note.png",
    title: "The Shared Token",
    subtitle: "A single ₹10 note, split in half",
    description:
      "One half stays with me, and the other is with you. A quiet promise that no matter the distance, we are always connected.",
    message:
      "Srividya, this isn't just a piece of paper; it's a shared secret. We split this ₹10 note to make a quiet promise: no matter where life takes us, or how far apart we might be, we each carry a piece of the exact same story. Hold onto your half (Serial No. 02D 648892). Because whenever you do, remember that you are holding onto a piece of my world. We are, and always will be, two halves of the same whole.",
    promise: "Some bonds are worth more than any currency. Ours is one of them.",
  },
} as const;
